''' <summary>Enum Representing Device Status</summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>08/02/2014 17:44:11</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Caerus\Enums\DeviceStatus.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Caerus\Enums\DeviceStatus.tt", "1")> _
Public Enum DeviceStatus As System.Int32

	''' <summary>Status is Unknown</summary>
	Unknown = 1

	''' <summary>Status is Running</summary>
	Running = 2

	''' <summary>Status is Warning</summary>
	Warning = 3

	''' <summary>Status is Testing</summary>
	Testing = 4

	''' <summary>Status is Down</summary>
	Down = 5

End Enum