''' <summary>Enum Representing Device Type</summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>08/02/2014 17:44:14</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Caerus\Enums\DeviceType.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Caerus\Enums\DeviceType.tt", "1")> _
Public Enum DeviceType As System.Int32

	''' <summary>Device Type is Other.</summary>
	Other = 1

	''' <summary>Device Type is Unknown.</summary>
	Unknown = 2

	''' <summary>Device Type is Processor.</summary>
	Processor = 3

	''' <summary>Device Type is Network.</summary>
	Network = 4

	''' <summary>Device Type is Printer.</summary>
	Printer = 5

	''' <summary>Device Type is Disk Storage.</summary>
	DiskStorage = 6

	''' <summary>Device Type is Video.</summary>
	Video = 10

	''' <summary>Device Type is Audio.</summary>
	Audio = 11

	''' <summary>Device Type is Coprocessor.</summary>
	Coprocessor = 12

	''' <summary>Device Type is Keyboard.</summary>
	Keyboard = 13

	''' <summary>Device Type is Modem.</summary>
	Modem = 14

	''' <summary>Device Type is Parallel Port.</summary>
	ParallelPort = 15

	''' <summary>Device Type is Pointing.</summary>
	Pointing = 16

	''' <summary>Device Type is Serial Port.</summary>
	SerialPort = 17

	''' <summary>Device Type is Tape.</summary>
	Tape = 18

	''' <summary>Device Type is Clock.</summary>
	Clock = 19

	''' <summary>Device Type is VolatileMemory.</summary>
	VolatileMemory = 20

	''' <summary>Device Type is NonVolatileMemory.</summary>
	NonVolatileMemory = 21

End Enum