''' <summary>Health Status Enumeration. This relies on the worst Health (e.g. down) being the lowest numerical value etc.</summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>08/02/2014 17:44:16</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Caerus\Enums\HealthStatus.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Caerus\Enums\HealthStatus.tt", "1")> _
Public Enum HealthStatus As System.Int32

	''' <summary>Status is Down</summary>
	Down = 1

	''' <summary>Status is Degraded</summary>
	Degraded = 2

	''' <summary>Status is Healthy</summary>
	Healthy = 3

End Enum