''' <summary>Enum Representing Interface Status</summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>08/02/2014 17:44:19</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Caerus\Enums\InterfaceStatus.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Caerus\Enums\InterfaceStatus.tt", "1")> _
Public Enum InterfaceStatus As System.Int32

	''' <summary>Status is Up.</summary>
	UP = 1

	''' <summary>Status is Down.</summary>
	DOWN = 2

	''' <summary>Status is Testing.</summary>
	TESTING = 3

	''' <summary>Status is Unknown.</summary>
	UNKNOWN = 4

	''' <summary>Status is Dormant.</summary>
	DORMANT = 5

	''' <summary>Status is Not Present.</summary>
	NOT_PRESENT = 6

	''' <summary>Status is Lower Layer Down.</summary>
	LOWER_LAYER_DOWN = 7

End Enum