''' <summary>Enum Representing Software Type</summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>08/02/2014 17:44:25</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Caerus\Enums\SoftwareType.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Caerus\Enums\SoftwareType.tt", "1")> _
Public Enum SoftwareType As System.Int32

	''' <summary>Software Type is Unknown.</summary>
	Unknown = 1

	''' <summary>Software Type is Operating System (OS).</summary>
	OperatingSystem = 2

	''' <summary>Software Type is Device Driver.</summary>
	DeviceDriver = 3

	''' <summary>Software Type is Application.</summary>
	Application = 4

End Enum