''' <summary>Enum Representing Storage Type</summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>08/02/2014 17:44:28</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Caerus\Enums\StorageType.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Caerus\Enums\StorageType.tt", "1")> _
Public Enum StorageType As System.Int32

	''' <summary>Type is None.</summary>
	None = 0

	''' <summary>Type is Other.</summary>
	Other = 1

	''' <summary>Type is Physical Memory.</summary>
	PhysicalMemory = 2

	''' <summary>Type is Virtual Memory.</summary>
	VirtualMemory = 3

	''' <summary>Type is Fixed Disk.</summary>
	FixedDisk = 4

	''' <summary>Type is Removable Disk.</summary>
	RemovableDisk = 5

	''' <summary>Type is Floppy Disk.</summary>
	FloppyDisk = 6

	''' <summary>Type is Compact Disk.</summary>
	CompactDisk = 7

	''' <summary>Type is Ram Disk.</summary>
	RamDisk = 8

	''' <summary>Type is Flash Disk.</summary>
	FlashDisk = 9

	''' <summary>Type is Network Disk.</summary>
	NetworkDisk = 10

End Enum