Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:23</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationRadioType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationRadioType.tt", "1")> _
	Public Enum AssociationRadioType As System.Int64

		''' <summary>PC3500</summary>
		PC3500 = 3

		''' <summary>PC3000</summary>
		PC3000 = 4

		''' <summary>PC4500</summary>
		PC4500 = 6

		''' <summary>PC4800</summary>
		PC4800 = 12

		''' <summary>PC3100</summary>
		PC3100 = 13

		''' <summary>Series340</summary>
		Series340 = 33

		''' <summary>Series350</summary>
		Series350 = 34

		''' <summary>Series370</summary>
		Series370 = 35

		''' <summary>Bridge1410</summary>
		Bridge1410 = 36

		''' <summary>MP2xSeries</summary>
		MP2xSeries = 37

		''' <summary>RM2xSeries</summary>
		RM2xSeries = 38

		''' <summary>RM2gSeries</summary>
		RM2gSeries = 39

		''' <summary>MP2xMAR</summary>
		MP2xMAR = 40

	End Enum

End Namespace