Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:19</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationClassType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationClassType.tt", "1")> _
	Public Enum AssociationClassType As System.Int64

		''' <summary>Client Station</summary>
		ClientStation = 0

		''' <summary>Repeater</summary>
		Repeater = 1

		''' <summary>Access Point</summary>
		AccessPoint = 2

		''' <summary>Bridge Host (WGB)</summary>
		BridgeHost = 3

		''' <summary>Bridge</summary>
		Bridge = 4

		''' <summary>Root Bridge</summary>
		BridgeRoot = 5

		''' <summary>Ethernet Client through WGB</summary>
		EthernetClient = 6

	End Enum

End Namespace