Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:22</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationKeyManagement.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationKeyManagement.tt", "1")> _
	<Flags()> _
	Public Enum AssociationKeyManagement As System.Int64

		''' <summary>WPA</summary>
		WPA = 128

		''' <summary>CCKM</summary>
		CCKM = 64

		''' <summary>All Flags</summary>
		All = WPA Or _
			CCKM

	End Enum

End Namespace