Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:21</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationIpAddressType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationIpAddressType.tt", "1")> _
	Public Enum AssociationIpAddressType As System.Int64

		''' <summary>Unknown</summary>
		Unknown = 0

		''' <summary>IPv4</summary>
		IPv4 = 1

		''' <summary>IPv6</summary>
		IPv6 = 2

		''' <summary>IPv4z</summary>
		IPv4z = 3

		''' <summary>IPv6z</summary>
		IPv6z = 4

		''' <summary>DNS</summary>
		DNS = 5

	End Enum

End Namespace