Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:24</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationState.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationState.tt", "1")> _
	Public Enum AssociationState As System.Int64

		''' <summary>Association request received from client</summary>
		Init = 1

		''' <summary>802.11 authenticated but not 802.11 associated</summary>
		Auth = 2

		''' <summary>802.11 associated and 802.1x authenticated</summary>
		AssocAuth = 3

		''' <summary>802.11 associated but 802.1x not authenticated</summary>
		Assoc = 4

	End Enum

End Namespace