Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:22</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationPowerSaveMode.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationPowerSaveMode.tt", "1")> _
	Public Enum AssociationPowerSaveMode As System.Int64

		''' <summary>Active</summary>
		Active = 1

		''' <summary>PowerSave</summary>
		PowerSave = 2

	End Enum

End Namespace