Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:16</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationAlgorithmType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationAlgorithmType.tt", "1")> _
	Public Enum AssociationAlgorithmType As System.Int64

		''' <summary>Open System</summary>
		Open = 1

		''' <summary>Shared Key</summary>
		SharedKey = 2

		''' <summary>Network EAP</summary>
		NetworkEap = 3

	End Enum

End Namespace