Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:20</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationDeviceType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationDeviceType.tt", "1")> _
	Public Enum AssociationDeviceType As System.Int64

		''' <summary>Ethernet Access Point</summary>
		EthernetAP = 76

		''' <summary>Ethernet Bridge</summary>
		EthernetBridge = 77

		''' <summary>Client with a 3000 Radio</summary>
		PC3000Client = 84

		''' <summary>Serial Port Universal Client</summary>
		SerialUC = 85

		''' <summary>Ethernet Universal Client</summary>
		EthernetUC = 86

		''' <summary>Client with 3500 Radio</summary>
		PC3500Client = 101

		''' <summary>Client of an Unknown Radio Type and Non-Cisco device</summary>
		Generic80211Client = 104

		''' <summary>Client with 4800 Radio</summary>
		PC4800Client = 109

		''' <summary>Client with 3100 Radio</summary>
		PC3100Client = 110

		''' <summary>Multiple-Client Ethernet</summary>
		MC = 111

		''' <summary>Ethernet Client of a WGB</summary>
		EthernetClient = 112

		''' <summary>Client with 4800b Radio</summary>
		PC4800bClient = 117

		''' <summary>WGB with one antenna</summary>
		WGBNoDiversity = 123

		''' <summary>WGB with two antennas</summary>
		WGB = 124

		''' <summary>Client with 350 series radio</summary>
		Series350Client = 127

		''' <summary>Client with 370 series radio</summary>
		Series370Client = 128

		''' <summary>Cisco 1100 series AP</summary>
		C1100SeriesAP = 129

		''' <summary>Cisco 1410 series bridge</summary>
		C1410SeriesBridge = 130

		''' <summary>Cisco 1200 series AP</summary>
		C1200SeriesAP = 132

		''' <summary>client with MP2x IEEE 802.11g radio</summary>
		MP2xClient = 133

		''' <summary>Cisco IOS 350 series AP</summary>
		C350SeriesAP = 134

		''' <summary>Cisco CB21AG/PI21AG IEEE 802.lla/b/g client</summary>
		CB21agClient = 135

		''' <summary>Cisco IEEE 802.11a AIR-RM21A-x-K9 and AIR-RM22A-x-K9 radio</summary>
		RadioKodiak = 136

		''' <summary>Cisco 1130 series AP</summary>
		C1130SeriesAP = 137

		''' <summary>Cisco 1310 series bridge</summary>
		C1310SeriesBridge = 138

		''' <summary>Cisco 7920 series phone</summary>
		C7920phone = 139

		''' <summary>Cisco 1240 series AP</summary>
		C1240SeriesAP = 140

	End Enum

End Namespace