Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:15</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\AssociationAdditionalAlgorthimType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\AssociationAdditionalAlgorthimType.tt", "1")> _
	<Flags()> _
	Public Enum AssociationAdditionalAlgorthimType As System.Int64

		''' <summary>MAC address authentication</summary>
		MAC = 128

		''' <summary>EAP authentication</summary>
		EAP = 64

		''' <summary>All Flags</summary>
		All = MAC Or _
			EAP

	End Enum

End Namespace