Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:24</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\BridgeAddressStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\BridgeAddressStatus.tt", "1")> _
	Public Enum BridgeAddressStatus As System.Int64

		''' <summary>None of the following. This would include the case where some other MIB object (not the corresponding instance of dot1dTpFdbPort, nor an entry in the dot1dStaticTable) is being used to determine if and how frames addressed to the value of the corresponding instance of dot1dTpFdbAddress are being forwarded.</summary>
		Other = 1

		''' <summary>This entry is not longer valid (e.g., it was learned but has since aged-out), but has not yet been flushed from the table.</summary>
		Invalid = 2

		''' <summary>The value of the corresponding instance of dot1dTpFdbPort was learned, and is being used.</summary>
		Learned = 3

		''' <summary>The value of the corresponding instance of dot1dTpFdbAddress represents one of the bridge's addresses.  The corresponding instance of dot1dTpFdbPort indicates which of the bridge's ports has this address.</summary>
		Self = 4

		''' <summary>The value of the corresponding instance of dot1dTpFdbAddress is also the value of an existing instance of dot1dStaticAddress.</summary>
		Mgmt = 5

	End Enum

End Namespace