Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:26</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\ClientType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\ClientType.tt", "1")> _
	Public Enum ClientType As System.Int64

		''' <summary>Unknown</summary>
		Unknown = 1

		''' <summary>EthernetAP</summary>
		EthernetAP = 76

		''' <summary>EthernetBridge</summary>
		EthernetBridge = 77

		''' <summary>PC3000Client</summary>
		PC3000Client = 84

		''' <summary>SerialUC</summary>
		SerialUC = 85

		''' <summary>EthernetUC</summary>
		EthernetUC = 86

		''' <summary>PC3500Client</summary>
		PC3500Client = 101

		''' <summary>PC4500Client</summary>
		PC4500Client = 102

		''' <summary>Generic80211Client</summary>
		Generic80211Client = 104

		''' <summary>PC4800Client</summary>
		PC4800Client = 109

		''' <summary>PC3100Client</summary>
		PC3100Client = 110

		''' <summary>MC</summary>
		MC = 111

		''' <summary>EthernetClient</summary>
		EthernetClient = 112

		''' <summary>PC4800bClient</summary>
		PC4800bClient = 117

		''' <summary>WgbNoDiversity</summary>
		WgbNoDiversity = 123

		''' <summary>Wgb</summary>
		Wgb = 124

		''' <summary>Series350Client</summary>
		Series350Client = 127

		''' <summary>Series370Client</summary>
		Series370Client = 128

		''' <summary>C1100SeriesAP</summary>
		C1100SeriesAP = 129

		''' <summary>C1410SeriesBridge</summary>
		C1410SeriesBridge = 130

		''' <summary>C1200SeriesAP</summary>
		C1200SeriesAP = 132

		''' <summary>Mp2xClient</summary>
		Mp2xClient = 133

		''' <summary>C350SeriesAP</summary>
		C350SeriesAP = 134

		''' <summary>Cb21agClient</summary>
		Cb21agClient = 135

		''' <summary>RadioKodiak</summary>
		RadioKodiak = 136

		''' <summary>C1130SeriesAP</summary>
		C1130SeriesAP = 137

		''' <summary>C1310SeriesBridge</summary>
		C1310SeriesBridge = 138

		''' <summary>C7920phone</summary>
		C7920phone = 139

		''' <summary>C1240SeriesAP</summary>
		C1240SeriesAP = 140

	End Enum

End Namespace