Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:25</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\ClientRole.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\ClientRole.tt", "1")> _
	Public Enum ClientRole As System.Int64

		''' <summary>ClientStation</summary>
		ClientStation = 0

		''' <summary>Repeater</summary>
		Repeater = 1

		''' <summary>AccessPoint</summary>
		AccessPoint = 2

		''' <summary>BridgeHost</summary>
		BridgeHost = 3

		''' <summary>Bridge</summary>
		Bridge = 4

		''' <summary>BridgeRoot</summary>
		BridgeRoot = 5

		''' <summary>EthernetClient</summary>
		EthernetClient = 6

	End Enum

End Namespace