Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:26</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\EnabledStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\EnabledStatus.tt", "1")> _
	Public Enum EnabledStatus As System.Int64

		''' <summary>NotPresent</summary>
		NotPresent = 0

		''' <summary>Enabled</summary>
		Enabled = 1

		''' <summary>Disabled</summary>
		Disabled = 2

	End Enum

End Namespace