Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:29</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\EnvironmentalMonitoringState.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\EnvironmentalMonitoringState.tt", "1")> _
	Public Enum EnvironmentalMonitoringState As System.Int64

		''' <summary>Normal</summary>
		Normal = 1

		''' <summary>Warning</summary>
		Warning = 2

		''' <summary>Critical</summary>
		Critical = 3

		''' <summary>Shutdown</summary>
		Shutdown = 4

		''' <summary>NotPresent</summary>
		NotPresent = 5

		''' <summary>NotFunctioning</summary>
		NotFunctioning = 6

	End Enum

End Namespace