Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:29</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\FrequencyUnits.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\FrequencyUnits.tt", "1")> _
	Public Enum FrequencyUnits As System.Int64

		''' <summary>NONE</summary>
		NONE = 0

		''' <summary>MHZ</summary>
		MHZ = 1

	End Enum

End Namespace