Namespace Cisco

	''' <summary>Enum Representing Hardware Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:30</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\HardwareType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\HardwareType.tt", "1")> _
	Public Enum HardwareType As System.Int64

		''' <summary>Hardware Type Is Other.</summary>
		Other = 1

		''' <summary>Hardware Type Is Unknown.</summary>
		Unknown = 2

		''' <summary>Hardware Type Is Chassis.</summary>
		Chassis = 3

		''' <summary>Hardware Type Is Backplane.</summary>
		Backplane = 4

		''' <summary>Hardware Type Is Container.</summary>
		Container = 5

		''' <summary>Hardware Type Is Power Supply.</summary>
		PowerSupply = 6

		''' <summary>Hardware Type Is Fan.</summary>
		Fan = 7

		''' <summary>Hardware Type Is Sensor.</summary>
		Sensor = 8

		''' <summary>Hardware Type Is Module.</summary>
		[Module] = 9

		''' <summary>Hardware Type Is Port.</summary>
		Port = 10

		''' <summary>Hardware Type Is Stack.</summary>
		Stack = 11

		''' <summary>Hardware Type Is CPU.</summary>
		CPU = 12

	End Enum

End Namespace