Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:33</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\IOSTrain.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\IOSTrain.tt", "1")> _
	Public Enum IOSTrain As System.Int64

		''' <summary>The mainline train is designed to be the most stable release the company can offer, and its feature set never expands during its lifetime. Updates are released only to address bugs in the product. The previous technology train becomes the source for the current mainline train — for example, the 12.1T train becomes the basis for the 12.2 mainline. Therefore, to determine the features available in a particular mainline release, look at the previous T train release.</summary>
		Mainline = 0

		''' <summary>Technology train, gets new features and bug fixes throughout its life, and is therefore less stable than the mainline. (In releases prior to Cisco IOS Release 12.0, the P train served as the Technology train.) Cisco doesn't recommend usage of T train in production environments unless there is urgency to implement a certain T train's new IOS feature.</summary>
		Technology = 1

		''' <summary>Service Provider train, runs only on the company's core router products and is heavily customized for Service Provider customers.</summary>
		ServiceProvider = 2

		''' <summary>Enterprise train, is customized for implementation in enterprise environments.</summary>
		Enterprise = 3

		''' <summary>Broadband train, support internet based broadband features.</summary>
		Broadband = 4

		''' <summary>The XA, XB ... special functionality train, needs to be documented</summary>
		SpecialFunctionality = 5

		''' <summary>Wireless (e.g. JA)</summary>
		Wireless = 6

		''' <summary>Train designed for specific needs.</summary>
		Other = 99

	End Enum

End Namespace