Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:34</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\RadioInterfacePhysicalType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\RadioInterfacePhysicalType.tt", "1")> _
	Public Enum RadioInterfacePhysicalType As System.Int64

		''' <summary>Unknown or Uninitialised</summary>
		UNKNOWN = 0

		''' <summary>Frequency Hopping, Spread Spectrum</summary>
		FHSS = 1

		''' <summary>Direct Sequence Spread Spectrum</summary>
		DSSS = 2

		''' <summary>Infrared Baseband</summary>
		IR_BASEBAND = 3

		''' <summary>Othogonal Frequency Division Multiplexing 802.11a</summary>
		OFDM = 4

		''' <summary>High Rate DSSS 802.11b</summary>
		HRDSSS = 5

		''' <summary>Extended Rate 802.11g</summary>
		ERP = 6

		''' <summary>High Throughput 802.11n</summary>
		HT = 7

	End Enum

End Namespace