Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:33</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\RadioInterfaceHtMode.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\RadioInterfaceHtMode.tt", "1")> _
	Public Enum RadioInterfaceHtMode As System.Int64

		''' <summary>No HT/802.11N Mode.</summary>
		None = 0

		''' <summary>In this mode, packets are transmitted in the legacy 802.11a/g format.</summary>
		Legacy = 1

		''' <summary>In this mode, packets are transmitted with a preamble that can be recognized by the legacy 802.11a/g devices. Both mixed mode and legacy packets can be recognised by the receiving 802.11n interface.</summary>
		Mixed = 2

		''' <summary>In this mode, a transmitting station won't add a preamble to the packets sent.</summary>
		GreenField = 3

	End Enum

End Namespace