Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:35</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\RadioInterfaceRoleType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\RadioInterfaceRoleType.tt", "1")> _
	Public Enum RadioInterfaceRoleType As System.Int64

		''' <summary>NONE</summary>
		NONE = 0

		''' <summary>WORKGROUP_BRIDGE</summary>
		WORKGROUP_BRIDGE = 1

		''' <summary>BRIDGE</summary>
		BRIDGE = 2

		''' <summary>CLIENT</summary>
		CLIENT = 3

		''' <summary>ROOT</summary>
		ROOT = 4

		''' <summary>REPEATER</summary>
		REPEATER = 5

		''' <summary>AP_BRIDGE</summary>
		AP_BRIDGE = 6

		''' <summary>AP_REPEATER</summary>
		AP_REPEATER = 7

		''' <summary>IBSS</summary>
		IBSS = 8

		''' <summary>NON_ROOT_BRIDGE</summary>
		NON_ROOT_BRIDGE = 9

		''' <summary>NON_ROOT_BRIDGE_AND_AP</summary>
		NON_ROOT_BRIDGE_AND_AP = 10

		''' <summary>SCANNER</summary>
		SCANNER = 11

	End Enum

End Namespace