Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:35</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\RadioMicAlgorithm.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\RadioMicAlgorithm.tt", "1")> _
	Public Enum RadioMicAlgorithm As System.Int64

		''' <summary>MIC_NONE</summary>
		MIC_NONE = 0

		''' <summary>MIC_MXX</summary>
		MIC_MXX = 2

		''' <summary>MIC_MICHAEL</summary>
		MIC_MICHAEL = 3

	End Enum

End Namespace