Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:40</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SecurityViolationAction.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SecurityViolationAction.tt", "1")> _
	Public Enum SecurityViolationAction As System.Int64

		''' <summary>NONE</summary>
		NONE = 0

		''' <summary>The interface will be forced to shut down.</summary>
		SHUTDOWN = 1

		''' <summary>The matched traffic will be dropped and cpsSecureMacAddrViolation notification will be generated.</summary>
		DROP_NOTIFY = 2

		''' <summary>The matched traffic will be dropped.</summary>
		DROP = 3

	End Enum

End Namespace