Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:37</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SecurityDot1xMode.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SecurityDot1xMode.tt", "1")> _
	Public Enum SecurityDot1xMode As System.Int64

		''' <summary>None</summary>
		NONE = 0

		''' <summary>Forced UnAuthorised</summary>
		FORCE_UNAUTH = 1

		''' <summary>Automatic</summary>
		AUTO = 2

		''' <summary>Forced Authorised</summary>
		FORCE_AUTH = 3

	End Enum

End Namespace