Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:38</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SecurityStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SecurityStatus.tt", "1")> _
	Public Enum SecurityStatus As System.Int64

		''' <summary>NONE</summary>
		NONE = 0

		''' <summary>This indicates port security is operational.</summary>
		SECURE_UP = 1

		''' <summary>This indicates port security is not operational. This happens when port security is configured to be enabled but could not be enabled due to certain reasons such as conflict with other features.</summary>
		SECURE_DOWN = 2

		''' <summary>This indicates that the port is shutdown due to port security violation when the object cpsIfViolationAction is of type 'shutdown'.</summary>
		SHUTDOWN = 3

	End Enum

End Namespace