Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:38</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SecurityDot1xStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SecurityDot1xStatus.tt", "1")> _
	Public Enum SecurityDot1xStatus As System.Int64

		''' <summary>NONE</summary>
		NONE = 0

		''' <summary>INITIALISE</summary>
		INITIALISE = 1

		''' <summary>DISCONNECTED</summary>
		DISCONNECTED = 2

		''' <summary>CONNECTING</summary>
		CONNECTING = 3

		''' <summary>AUTHENTICATING</summary>
		AUTHENTICATING = 4

		''' <summary>AUTHENTICATED</summary>
		AUTHENTICATED = 5

		''' <summary>ABORTING</summary>
		ABORTING = 6

		''' <summary>HELD</summary>
		HELD = 7

		''' <summary>FORCE_AUTH</summary>
		FORCE_AUTH = 8

		''' <summary>FORCE_UNAUTH</summary>
		FORCE_UNAUTH = 9

	End Enum

End Namespace