Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:42</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SensorThresholdRelation.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SensorThresholdRelation.tt", "1")> _
	Public Enum SensorThresholdRelation As System.Int64

		''' <summary>LessThan</summary>
		LessThan = 1

		''' <summary>LessThanOrEqual</summary>
		LessThanOrEqual = 2

		''' <summary>GreaterThan</summary>
		GreaterThan = 3

		''' <summary>GreaterThanOrEqual</summary>
		GreaterThanOrEqual = 4

		''' <summary>EqualTo</summary>
		EqualTo = 5

		''' <summary>NotEqualTo</summary>
		NotEqualTo = 6

	End Enum

End Namespace