Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:43</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SensorUnits.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SensorUnits.tt", "1")> _
	Public Enum SensorUnits As System.Int64

		''' <summary>None</summary>
		None = 0

		''' <summary>Other</summary>
		Other = 1

		''' <summary>Unknown</summary>
		Unknown = 2

		''' <summary>VoltsAC</summary>
		VoltsAC = 3

		''' <summary>VoltsDC</summary>
		VoltsDC = 4

		''' <summary>Amperes</summary>
		Amperes = 5

		''' <summary>Watts</summary>
		Watts = 6

		''' <summary>Hertz</summary>
		Hertz = 7

		''' <summary>Celsius</summary>
		Celsius = 8

		''' <summary>PercentRH</summary>
		PercentRH = 9

		''' <summary>RPM</summary>
		RPM = 10

		''' <summary>CMM</summary>
		CMM = 11

		''' <summary>Boolean</summary>
		[Boolean] = 12

		''' <summary>SpecialEnum</summary>
		SpecialEnum = 13

		''' <summary>DBM</summary>
		DBM = 14

	End Enum

End Namespace