Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:42</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SensorStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SensorStatus.tt", "1")> _
	Public Enum SensorStatus As System.Int64

		''' <summary>Ok</summary>
		Ok = 1

		''' <summary>Unavailable</summary>
		Unavailable = 2

		''' <summary>NonOperational</summary>
		NonOperational = 3

	End Enum

End Namespace