Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:41</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SensorScale.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SensorScale.tt", "1")> _
	Public Enum SensorScale As System.Int64

		''' <summary>Yocto</summary>
		Yocto = 1

		''' <summary>Zepto</summary>
		Zepto = 2

		''' <summary>Atto</summary>
		Atto = 3

		''' <summary>Femto</summary>
		Femto = 4

		''' <summary>Pico</summary>
		Pico = 5

		''' <summary>Nano</summary>
		Nano = 6

		''' <summary>Micro</summary>
		Micro = 7

		''' <summary>Milli</summary>
		Milli = 8

		''' <summary>Units</summary>
		Units = 9

		''' <summary>Kilo</summary>
		Kilo = 10

		''' <summary>Mega</summary>
		Mega = 11

		''' <summary>Giga</summary>
		Giga = 12

		''' <summary>Tera</summary>
		Tera = 13

		''' <summary>Exa</summary>
		Exa = 14

		''' <summary>Peta</summary>
		Peta = 15

		''' <summary>Zetta</summary>
		Zetta = 16

		''' <summary>Yotta</summary>
		Yotta = 17

	End Enum

End Namespace