Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:43</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\SensorThresholdSeverity.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\SensorThresholdSeverity.tt", "1")> _
	Public Enum SensorThresholdSeverity As System.Int64

		''' <summary>Other</summary>
		Other = 1

		''' <summary>Minor</summary>
		Minor = 10

		''' <summary>Major</summary>
		Major = 20

		''' <summary>Critical</summary>
		Critical = 30

	End Enum

End Namespace