Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:47</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\VlanState.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\VlanState.tt", "1")> _
	Public Enum VlanState As System.Int64

		''' <summary>NONE</summary>
		NONE = 0

		''' <summary>OPERATIONAL</summary>
		OPERATIONAL = 1

		''' <summary>SUSPENDED</summary>
		SUSPENDED = 2

		''' <summary>MTU_TOO_BIG_FOR_DEVICE</summary>
		MTU_TOO_BIG_FOR_DEVICE = 3

		''' <summary>MTU_TOO_BIG_FOR_TRUNK</summary>
		MTU_TOO_BIG_FOR_TRUNK = 4

	End Enum

End Namespace