Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:48</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\VlanType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\VlanType.tt", "1")> _
	Public Enum VlanType As System.Int64

		''' <summary>NONE</summary>
		NONE = 0

		''' <summary>ETHERNET</summary>
		ETHERNET = 1

		''' <summary>FDDI</summary>
		FDDI = 2

		''' <summary>TOKENRING</summary>
		TOKENRING = 3

		''' <summary>FDDINET</summary>
		FDDINET = 4

		''' <summary>TRNET</summary>
		TRNET = 5

		''' <summary>DEPRECATED</summary>
		DEPRECATED = 6

	End Enum

End Namespace