Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 17:53:45</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Enums\VlanMembershipType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Enums\VlanMembershipType.tt", "1")> _
	Public Enum VlanMembershipType As System.Int64

		''' <summary>NONE</summary>
		NONE = 0

		''' <summary>STATIC</summary>
		[STATIC] = 1

		''' <summary>DYNAMIC</summary>
		DYNAMIC = 2

		''' <summary>MULTI_VLAN</summary>
		MULTI_VLAN = 3

	End Enum

End Namespace