Namespace IBM

	''' <summary>Enum Representing IBM Blade State</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:20:28</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_IBM\Enums\BladeState.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_IBM\Enums\BladeState.tt", "1")> _
	Public Enum BladeState As System.Int32

		''' <summary>Status is Unknown</summary>
		Unknown = 0

		''' <summary>Status is Good</summary>
		Good = 1

		''' <summary>Status is Warning</summary>
		Warning = 2

		''' <summary>Status is Bad</summary>
		Bad = 3

	End Enum

End Namespace