Namespace Exterity

	''' <summary>Enum Representing Exterity Device Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:02</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\DeviceType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\DeviceType.tt", "1")> _
	Public Enum DeviceType As System.Int64

		''' <summary>Type is Encoder</summary>
		Encoder = 1

		''' <summary>Type is Decoder</summary>
		Decoder = 2

		''' <summary>Type is TV Gateway</summary>
		TVGateway = 3

		''' <summary>Type is Avedia Server</summary>
		AvediaServer = 4

	End Enum

End Namespace