Namespace Exterity

	''' <summary>Enum Representing Exterity Display Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:03</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\DisplayType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\DisplayType.tt", "1")> _
	Public Enum DisplayType As System.Int64

		''' <summary>Display Type is TV</summary>
		TV = 0

		''' <summary>Display Type is Browser</summary>
		Browser = 1

		''' <summary>Display Type is Splash</summary>
		Splash = 2

		''' <summary>Display Type is Playlist</summary>
		Playlist = 3

		''' <summary>Display Type is Off</summary>
		Off = 4

	End Enum

End Namespace