Namespace Exterity

	''' <summary>Enum Representing Exterity Line Speed</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:10</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\LineSpeed.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\LineSpeed.tt", "1")> _
	Public Enum LineSpeed As System.Int64

		''' <summary>Ten Megabits</summary>
		_10Mbits = 0

		''' <summary>One Hundred MegaBits</summary>
		_100Mbits = 1

	End Enum

End Namespace