Namespace Exterity

	''' <summary>Enum Representing Exterity Line Duplex</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:09</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\LineDuplex.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\LineDuplex.tt", "1")> _
	Public Enum LineDuplex As System.Int64

		''' <summary>Half-Duplex Line</summary>
		Half = 0

		''' <summary>Full-Duplex Line</summary>
		Full = 1

	End Enum

End Namespace