Namespace Exterity

	''' <summary>Enum Representing Exterity Proxy Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:11</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\ProxyType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\ProxyType.tt", "1")> _
	Public Enum ProxyType As System.Int64

		''' <summary>Proxy Type is Direct (e.g. No Proxy)</summary>
		Direct = 0

		''' <summary>Proxy Type is manually defined</summary>
		Manual = 1

	End Enum

End Namespace