Namespace Exterity

	''' <summary>Enum Representing Exterity Service Status</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:13</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\ServiceStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\ServiceStatus.tt", "1")> _
	Public Enum ServiceStatus As System.Int64

		''' <summary>Service Status is Unknown</summary>
		Unknown = 0

		''' <summary>Service Status is Stopped</summary>
		Stopped = 1

		''' <summary>Service Status is Started</summary>
		Started = 2

	End Enum

End Namespace