Namespace Exterity

	''' <summary>Enum Representing Exterity Stream Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:14</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\StreamType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\StreamType.tt", "1")> _
	Public Enum StreamType As System.Int64

		''' <summary>Stream Type is Elementary</summary>
		Elementary = 0

		''' <summary>Stream Type is Transport</summary>
		Transport = 1

	End Enum

End Namespace