Namespace Exterity

	''' <summary>Enum Representing Exterity Test Status</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:15</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\TestStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\TestStatus.tt", "1")> _
	Public Enum TestStatus As System.Int64

		''' <summary>Test Status is Failed</summary>
		Failed = 1

		''' <summary>Test has not been performed</summary>
		NotPerformed = 0

		''' <summary>Test Status is Passed</summary>
		Passed = 1

	End Enum

End Namespace