Namespace Exterity

	''' <summary>Enum Representing Exterity Video Aspect Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:17</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\VideoAspectType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\VideoAspectType.tt", "1")> _
	Public Enum VideoAspectType As System.Int64

		''' <summary>Type is Off</summary>
		Off = 0

		''' <summary>Type is Normal (4:3)</summary>
		Normal = 1

		''' <summary>Type is Wide (16:9)</summary>
		Wide = 2

	End Enum

End Namespace