Namespace Exterity

	''' <summary>Enum Representing Exterity Video Interface Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:21</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\VideoInterfaceType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\VideoInterfaceType.tt", "1")> _
	Public Enum VideoInterfaceType As System.Int64

		''' <summary>Type is Composite</summary>
		Composite = 0

		''' <summary>Type is RBG</summary>
		RGB = 1

		''' <summary>Type is S-Video</summary>
		SVideo = 2

		''' <summary>Type is Pb-Pr</summary>
		PbPr = 3

	End Enum

End Namespace