Namespace Exterity

	''' <summary>Enum Representing Exterity Video Bitrate Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:19</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\VideoBitrateType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\VideoBitrateType.tt", "1")> _
	Public Enum VideoBitrateType As System.Int64

		''' <summary>Type is Constant Bitrate.</summary>
		Constant = 0

		''' <summary>Type is Variable Bitrate.</summary>
		[Variable] = 1

	End Enum

End Namespace