Namespace Exterity

	''' <summary>Enum Representing Exterity Video Format Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:13:20</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Exterity\Enums\VideoFormatType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Exterity\Enums\VideoFormatType.tt", "1")> _
	Public Enum VideoFormatType As System.Int64

		''' <summary>Type is None</summary>
		None = 1

		''' <summary>Type is PAL</summary>
		PAL = 0

		''' <summary>Type is NTSC</summary>
		NTSC = 1

		''' <summary>Type is SECAM</summary>
		SECAM = 2

		''' <summary>Type is Black and White</summary>
		BW = 3

	End Enum

End Namespace