Namespace QNAP

	''' <summary>Enum Representing NAP Hard-Drive Status</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:24:16</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_QNAP\Enums\HDStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_QNAP\Enums\HDStatus.tt", "1")> _
	Public Enum HDStatus As System.Int64

		''' <summary>READY</summary>
		READY = 0

		''' <summary>NO_DISK</summary>
		NO_DISK = 2

		''' <summary>INVALID</summary>
		INVALID = 3

		''' <summary>RW_ERROR</summary>
		RW_ERROR = 4

		''' <summary>UNKNOWN</summary>
		UNKNOWN = 5

	End Enum

End Namespace