Namespace Snmp

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:26:13</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Snmp\Enums\SnmpDisplayVersion.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Snmp\Enums\SnmpDisplayVersion.tt", "1")> _
	Public Enum SnmpDisplayVersion As System.Int32

		''' <summary>v1</summary>
		v1 = 1

		''' <summary>v2</summary>
		v2 = 2

		''' <summary>v2c</summary>
		v2c = 3

		''' <summary>v2p</summary>
		v2p = 4

		''' <summary>v3</summary>
		v3 = 5

	End Enum

End Namespace