Namespace Snmp

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:26:14</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Snmp\Enums\SnmpVersion.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Snmp\Enums\SnmpVersion.tt", "1")> _
	Public Enum SnmpVersion As System.Byte

		''' <summary>SNMP_VERSION_1</summary>
		SNMP_VERSION_1 = 0

		''' <summary>SNMP_VERSION_2C</summary>
		SNMP_VERSION_2C = 1

		''' <summary>SNMP_VERSION_2P</summary>
		SNMP_VERSION_2P = 2

		''' <summary>SNMP_VERSION_3</summary>
		SNMP_VERSION_3 = 3

	End Enum

End Namespace