Namespace Snmp

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:26:14</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Snmp\Enums\SnmpMessageType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Snmp\Enums\SnmpMessageType.tt", "1")> _
	Public Enum SnmpMessageType As System.Int32

		''' <summary>GET_REQUEST</summary>
		GET_REQUEST = 0

		''' <summary>GET_NEXT_REQUEST</summary>
		GET_NEXT_REQUEST = 1

		''' <summary>GET_RESPONSE</summary>
		GET_RESPONSE = 2

		''' <summary>SET_REQUEST</summary>
		SET_REQUEST = 3

		''' <summary>TRAP_V1</summary>
		TRAP_V1 = 4

		''' <summary>GET_BULK_REQUEST</summary>
		GET_BULK_REQUEST = 5

		''' <summary>INFORM_REQUEST</summary>
		INFORM_REQUEST = 6

		''' <summary>TRAP_V2</summary>
		TRAP_V2 = 7

		''' <summary>REPORT</summary>
		REPORT = 8

	End Enum

End Namespace