Namespace Snmp

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:26:12</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Snmp\Enums\SnmpDataType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Snmp\Enums\SnmpDataType.tt", "1")> _
	Public Enum SnmpDataType As System.Byte

		''' <summary>ASN1_BOOLEAN</summary>
		ASN1_BOOLEAN = 1

		''' <summary>ASN1_INTEGER</summary>
		ASN1_INTEGER = 2

		''' <summary>ASN1_BIT_STRING</summary>
		ASN1_BIT_STRING = 3

		''' <summary>ASN1_OCTET_STRING</summary>
		ASN1_OCTET_STRING = 4

		''' <summary>ASN1_NULL</summary>
		ASN1_NULL = 5

		''' <summary>ASN1_OBJECT_IDENTIFIER</summary>
		ASN1_OBJECT_IDENTIFIER = 6

		''' <summary>ASN1_REAL</summary>
		ASN1_REAL = 9

		''' <summary>ASN1_ENUMERATED</summary>
		ASN1_ENUMERATED = 16

		''' <summary>ASN1_SET</summary>
		ASN1_SET = 17

		''' <summary>ASN1_PRINTABLE_STRING</summary>
		ASN1_PRINTABLE_STRING = 19

		''' <summary>ASN1_T61_STRING</summary>
		ASN1_T61_STRING = 20

		''' <summary>ASN1_IA5_STRING</summary>
		ASN1_IA5_STRING = 22

		''' <summary>ASN1_UTC_TIME</summary>
		ASN1_UTC_TIME = 23

		''' <summary>ASN1_SEQUENCE</summary>
		ASN1_SEQUENCE = 48

		''' <summary>SNMP_IP_ADDRESS</summary>
		SNMP_IP_ADDRESS = 64

		''' <summary>SNMP_COUNTER_32</summary>
		SNMP_COUNTER_32 = 65

		''' <summary>SNMP_GAUGE</summary>
		SNMP_GAUGE = 66

		''' <summary>SNMP_TIMETICKS</summary>
		SNMP_TIMETICKS = 67

		''' <summary>SNMP_OPAQUE</summary>
		SNMP_OPAQUE = 68

		''' <summary>SNMP_PHYSICAL_ADDRESS</summary>
		SNMP_PHYSICAL_ADDRESS = 69

		''' <summary>SNMP_COUNTER_64</summary>
		SNMP_COUNTER_64 = 70

		''' <summary>SNMP_UNIT_32</summary>
		SNMP_UNIT_32 = 71

		''' <summary>SNMP_PDU_GETREQUEST</summary>
		SNMP_PDU_GETREQUEST = 160

		''' <summary>SNMP_PDU_GETNEXTREQUEST</summary>
		SNMP_PDU_GETNEXTREQUEST = 161

		''' <summary>SNMP_PDU_GETRESPONSE</summary>
		SNMP_PDU_GETRESPONSE = 162

		''' <summary>SNMP_PDU_SETREQUEST</summary>
		SNMP_PDU_SETREQUEST = 163

		''' <summary>SNMP_PDU_TRAP</summary>
		SNMP_PDU_TRAP = 164

		''' <summary>SNMP_PDU_GETBULKREQUEST</summary>
		SNMP_PDU_GETBULKREQUEST = 165

		''' <summary>SNMP_PDU_INFORMREQUEST</summary>
		SNMP_PDU_INFORMREQUEST = 166

		''' <summary>SNMP_PDU_TRAPV2</summary>
		SNMP_PDU_TRAPV2 = 167

	End Enum

End Namespace