Namespace Snmp

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:26:13</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Snmp\Enums\SnmpErrorStatus.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Snmp\Enums\SnmpErrorStatus.tt", "1")> _
	Public Enum SnmpErrorStatus As System.Int32

		''' <summary>No error occurred. This code is also used in all request PDUs, since they have no error status to report</summary>
		NO_ERROR = 0

		''' <summary>The size of the Response-PDU would be too large to transport</summary>
		TOO_BIG = 1

		''' <summary>The name of a requested object was not found</summary>
		NO_SUCH_NAME = 2

		''' <summary>A value in the request didn't match the structure that the recipient of the request had for the object. For example, an object in the request was specified with an incorrect length or type</summary>
		BAD_VALUE = 3

		''' <summary>An attempt was made to set a variable that has an Access value indicating that it is read-only</summary>
		READ_ONLY = 4

		''' <summary>An error occurred other than one indicated by a more specific error code in this table</summary>
		GENERAL_ERROR = 5

		''' <summary>Access was denied to the object for security reasons</summary>
		NO_ACCESS = 6

		''' <summary>The object type in a variable binding is incorrect for the object</summary>
		WRONG_TYPE = 7

		''' <summary>A variable binding specifies a length incorrect for the object</summary>
		WRONG_LENGTH = 8

		''' <summary>A variable binding specifies an encoding incorrect for the object</summary>
		WRONG_ENCODING = 9

		''' <summary>The value given in a variable binding is not possible for the object</summary>
		WRONG_VALUE = 10

		''' <summary>A specified variable does not exist and cannot be created</summary>
		NO_CREATION = 11

		''' <summary>A variable binding specifies a value that could be held by the variable but cannot be assigned to it at this time</summary>
		INCONSISTENT_VALUE = 12

		''' <summary>An attempt to set a variable required a resource that is not available</summary>
		RESOURCE_UNAVAILABLE = 13

		''' <summary>An attempt to set a particular variable failed</summary>
		COMMIT_FAILED = 14

		''' <summary>An attempt to set a particular variable as part of a group of variables failed, and the attempt to then undo the setting of other variables was not successful</summary>
		UNDO_FAILED = 15

		''' <summary>A problem occurred in authorization</summary>
		AUTHORISATION_ERROR = 16

		''' <summary>The variable cannot be written or created</summary>
		NOT_WRITABLE = 17

		''' <summary>The name in a variable binding specifies a variable that does not exist</summary>
		INCONSISTENT_NAME = 18

	End Enum

End Namespace