Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:05:32</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Voice\Enums\CiscoIPPhoneErrorCodes.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Voice\Enums\CiscoIPPhoneErrorCodes.tt", "1")> _
	Public Enum CiscoIPPhoneErrorCodes As System.Int64

		''' <summary>CiscoIPPhoneExecuteParsingError</summary>
		CiscoIPPhoneExecuteParsingError = 1

		''' <summary>CiscoIPPhoneResponseResponseFramingError</summary>
		CiscoIPPhoneResponseResponseFramingError = 2

		''' <summary>InternalError</summary>
		InternalError = 3

		''' <summary>AuthenticationError</summary>
		AuthenticationError = 4

	End Enum

End Namespace