Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:05:33</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Voice\Enums\CiscoIPPhoneInputItemFlags.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Voice\Enums\CiscoIPPhoneInputItemFlags.tt", "1")> _
	Public Enum CiscoIPPhoneInputItemFlags As System.Int64

		''' <summary>Nothing</summary>
		[Nothing] = 0

		''' <summary>AlphaNumeric</summary>
		AlphaNumeric = 1

		''' <summary>Numeric</summary>
		Numeric = 2

		''' <summary>UpperCaseAlpha</summary>
		UpperCaseAlpha = 3

		''' <summary>LowerCaseAlpha</summary>
		LowerCaseAlpha = 4

	End Enum

End Namespace