Namespace Cisco

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:05:34</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Cisco\Voice\Enums\CiscoIPPhoneSoftKeyURI.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Cisco\Voice\Enums\CiscoIPPhoneSoftKeyURI.tt", "1")> _
	Public Enum CiscoIPPhoneSoftKeyURI As System.Int64

		''' <summary>Nothing</summary>
		[Nothing] = 0

		''' <summary>Select</summary>
		[Select] = 1

		''' <summary>Update</summary>
		Update = 2

		''' <summary>Submit</summary>
		Submit = 3

		''' <summary>Back</summary>
		Back = 4

		''' <summary>Forward</summary>
		Forward = 5

		''' <summary>Cancel</summary>
		Cancel = 6

		''' <summary>Dial</summary>
		Dial = 7

		''' <summary>EditDial</summary>
		EditDial = 8

		''' <summary>Exit</summary>
		[Exit] = 9

	End Enum

End Namespace