Namespace Directories

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:09:16</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Directories\Enums\AccountOptions.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Directories\Enums\AccountOptions.tt", "1")> _
	<Flags()> _
	Public Enum AccountOptions As System.Int32

		''' <summary>The logon script executed</summary>
		UF_SCRIPT = 1

		''' <summary>The user's account is disabled</summary>
		UF_ACCOUNTDISABLE = 2

		''' <summary>The home directory is required. This value is ignored</summary>
		UF_HOMEDIR_REQUIRED = 8

		''' <summary>The account is currently locked out</summary>
		UF_ACCOUNT_LOCKOUT = 16

		''' <summary>The user's password has expired</summary>
		UF_PASSWD_NOTREQD = 32

		''' <summary>The user cannot change the password</summary>
		UF_PASSWD_CANT_CHANGE = 64

		''' <summary>The user's password is stored under reversible encryption in the Active Directory</summary>
		UF_ENCRYPTED_TEXT_PASSWORD_ALLOWED = 128

		''' <summary>Local user account for users who have a primary account in another domain. This account provides user access to this domain only—not to any domain that trusts this domain.</summary>
		UF_TEMP_DUPLICATE_ACCOUNT = 256

		''' <summary>Default account type that represents a typical user</summary>
		UF_NORMAL_ACCOUNT = 512

		''' <summary>Account for a system domain that trusts other domains</summary>
		UF_INTERDOMAIN_TRUST_ACCOUNT = 2048

		''' <summary>Computer account for a Windows NT/Windows 2000 computer that is a member of this domain</summary>
		UF_WORKSTATION_TRUST_ACCOUNT = 4096

		''' <summary>Account for a system backup domain controller that is a member of this domain</summary>
		UF_SERVER_TRUST_ACCOUNT = 8192

		''' <summary>The password should never expire on the account</summary>
		UF_DONT_EXPIRE_PASSWD = 65536

		''' <summary>All Flags</summary>
		All = UF_SCRIPT Or _
			UF_ACCOUNTDISABLE Or _
			UF_HOMEDIR_REQUIRED Or _
			UF_ACCOUNT_LOCKOUT Or _
			UF_PASSWD_NOTREQD Or _
			UF_PASSWD_CANT_CHANGE Or _
			UF_ENCRYPTED_TEXT_PASSWORD_ALLOWED Or _
			UF_TEMP_DUPLICATE_ACCOUNT Or _
			UF_NORMAL_ACCOUNT Or _
			UF_INTERDOMAIN_TRUST_ACCOUNT Or _
			UF_WORKSTATION_TRUST_ACCOUNT Or _
			UF_SERVER_TRUST_ACCOUNT Or _
			UF_DONT_EXPIRE_PASSWD

	End Enum

End Namespace