Namespace Directories

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:09:17</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Directories\Enums\AuthenticationType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Directories\Enums\AuthenticationType.tt", "1")> _
	<System.Serializable()> _
	Public Enum AuthenticationType As System.Int32

		''' <summary>Authentication Performed Anonymously (Without Credentials)</summary>
		Anonymous = 1

		''' <summary>Authentication Performed Integrated (Process Level Credentials)</summary>
		Integrated = 2

		''' <summary>Authentication Performed with Supplied Username and Password (Basic Credentials)</summary>
		Basic = 3

	End Enum

End Namespace