Namespace Directories

	''' <summary>This Enum is used to help define the Common Schemas for Directory Entry Manipulation</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:09:23</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Directories\Enums\CommonSchemas.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Directories\Enums\CommonSchemas.tt", "1")> _
	<System.Serializable()> _
	Public Enum CommonSchemas As System.Int32

		''' <summary>The Schema of a User</summary>
		User = 1

		''' <summary>The Schema of a DNS Domain</summary>
		DNSDomain = 2

		''' <summary>The Schema of a Group</summary>
		Group = 3

	End Enum

End Namespace