Namespace Directories

	''' <summary>This Enum is used to help define the Common Actions for Directory Entry Manipulation</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:09:19</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Directories\Enums\CommonActions.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Directories\Enums\CommonActions.tt", "1")> _
	<System.Serializable()> _
	Public Enum CommonActions As System.Int32

		''' <summary>The Set Password Action</summary>
		SetPassword = 1

		''' <summary>The Disabled Password Action</summary>
		DisabledAccount = 2

		''' <summary>The Locked Account Action</summary>
		LockedAccount = 3

		''' <summary>The Required Password Action</summary>
		RequiredPassword = 4

	End Enum

End Namespace