Namespace Directories

	''' <summary>This Enum is used to help define the Common Properties for Directory Entry Manipulation</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>30/08/2014 17:12:11</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Directories\Enums\CommonProperties.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Directories\Enums\CommonProperties.tt", "1")> _
	<System.Serializable()> _
	Public Enum CommonProperties As System.Int32

		''' <summary>The Username of a Directory Account</summary>
		AccountUsername = 1

		''' <summary>The Display Name of a Directory Account</summary>
		DisplayName = 2

		''' <summary>The Given Name of a Directory Account</summary>
		GivenName = 3

		''' <summary>The Surname of a Directory Account</summary>
		Surname = 4

		''' <summary>The Home Directory of a Directory Account</summary>
		HomeDirectory = 5

		''' <summary>The Home Drive of a Directory Account</summary>
		HomeDirectoryDrive = 6

		''' <summary>The Profile Directory of a Directory Account</summary>
		ProfileDirectory = 7

		''' <summary>The Principle Name of a Directory Account</summary>
		PrincipleName = 8

		''' <summary>The Employee Identifier of a Directory Account</summary>
		EmployeeIdentifier = 9

		''' <summary>The Department of a Directory Account</summary>
		Department = 10

		''' <summary>The Common Name of a Directory Entry</summary>
		CommonName = 11

		''' <summary>The Description of a Directory Entry</summary>
		Description = 12

		''' <summary>The Description of a Domain Controller</summary>
		DomainController = 13

		''' <summary>The Extension Name of a Directory Entry</summary>
		ExtensionName = 14

		''' <summary>The Object Class of a Directory Entry</summary>
		ObjectClass = 15

		''' <summary>The Object Category of a Directory Entry</summary>
		ObjectCategory = 16

		''' <summary>The Unicode Password of a Directory Entry</summary>
		UnicodePassword = 17

		''' <summary>The LockOut Time of a Directory Entry</summary>
		LockOutTime = 18

	End Enum

End Namespace