Namespace Directories

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:09:26</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Directories\Enums\ParameterComparator.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Directories\Enums\ParameterComparator.tt", "1")> _
	<System.Serializable()> _
	Public Enum ParameterComparator As System.Int32

		''' <summary>Represents an Equality Operator</summary>
		EqualTo = 1

		''' <summary>Represents an Approximate Equality Operator</summary>
		ApproximatelyEqualTo = 2

		''' <summary>Represents a Less-Than Or Equality Operator</summary>
		LessThanOrEqualTo = 3

		''' <summary>Represents a Greater-Than Or Equality Operator</summary>
		GreaterThanOrEqualTo = 4

	End Enum

End Namespace