Namespace Directories

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:09:27</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Directories\Enums\ParameterOperator.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Directories\Enums\ParameterOperator.tt", "1")> _
	<System.Serializable()> _
	Public Enum ParameterOperator As System.Int32

		''' <summary>Represents an AND Operator</summary>
		AndOperator = 1

		''' <summary>Represents an OR Operator</summary>
		OrEquality = 2

		''' <summary>Represents a NOT Operator</summary>
		NotEquality = 3

	End Enum

End Namespace