Namespace Directories

	''' <summary>This Enum is used to help define the Scope of Directory Services Searches</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>08/02/2014 18:09:29</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Caerus\_Directories\Enums\SearchScope.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Caerus\_Directories\Enums\SearchScope.tt", "1")> _
	<System.Serializable()> _
	Public Enum SearchScope As System.Int32

		''' <summary>Indicates that a Search should be performed at the Base Level only</summary>
		Base = 1

		''' <summary>Indicates that a Search should be performed at the Base Level and One Level below only</summary>
		OneLevel = 2

		''' <summary>Indicates that a Search should be performed at the Base Level and all Levels below</summary>
		SubTree = 3

	End Enum

End Namespace